---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_management_node.html 
summary: Come parte di un aggiornamento del sistema NetApp HCI, si aggiorna il nodo di gestione. 
keywords: netapp, hci, on premise, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x, 12.5, 12.7, 12.8 
---
= Aggiornare un nodo di gestione
:allow-uri-read: 


[role="lead"]
È possibile aggiornare il nodo di gestione al nodo di gestione 12.5 o successivo dalla versione 12.3.x o successiva.

L'aggiornamento del sistema operativo del nodo di gestione non è più necessario per aggiornare il software Element sul cluster di storage. Puoi semplicemente aggiornare i servizi di gestione alla versione più recente per eseguire gli aggiornamenti degli elementi utilizzando NetApp Hybrid Cloud Control. Se si desidera aggiornare il sistema operativo del nodo di gestione per altri motivi, ad esempio la risoluzione dei problemi di protezione, seguire la procedura di aggiornamento del nodo di gestione per lo scenario in uso.


NOTE: Per informazioni sull'aggiornamento dei nodi di gestione 12.2 o versioni precedenti, consultare https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_management_node.html["Documentazione sull'aggiornamento del nodo di gestione di NetApp HCI 1.9"^].



== Fase 1: Aggiornare la versione hardware della macchina virtuale su un nodo di gestione

Se si sta eseguendo un aggiornamento sul posto di un nodo di gestione esistente all'elemento 12,8, prima di eseguire l'aggiornamento, è necessario assicurarsi che la versione hardware della VM sul nodo di gestione sia compatibile con ESXi 6,7 (VM hardware versione 14) o successiva, a seconda dell'ambiente in uso.


NOTE: È anche possibile seguire questi passaggi per aggiornare la versione hardware della VM sui nodi di controllo.

.Fasi
. Accedere a vSphere Web Client come vCenter Administrator.
. Dal menu vSphere Client, selezionare *VM* e *modelli*.
. Fare clic con il pulsante destro del mouse sulla macchina virtuale e selezionare *compatibilità* > *Aggiorna compatibilità VM*.
. Selezionare *Sì*.
. Selezionare ESXi 6,7 o una versione successiva, a seconda della versione dell'ambiente vSphere in uso.
. Selezionare *OK*.
. Al termine dell'aggiornamento, selezionare *vSphere client refresh* e verificare che la compatibilità VM sia la versione desiderata.




== Passaggio 2: Aggiornare un nodo di gestione a Element 12,5 o versione successiva

Scegliere una delle seguenti opzioni di aggiornamento:

* <<Aggiornare un nodo di gestione alla versione 12.5 o successiva dalla versione 12.3.x o successiva>>
* <<Riconfigurare l'autenticazione utilizzando l'API REST del nodo di gestione>>
+
Scegli questa opzione se hai aggiornato in modo *sequenziale* (1) la versione dei servizi di gestione e (2) la versione dello storage Element e vuoi mantenere * il nodo di gestione esistente:




NOTE: Se non si aggiornano in sequenza i servizi di gestione seguiti dallo storage degli elementi, non è possibile riconfigurare la riautenticazione utilizzando questa procedura. Seguire invece la procedura di aggiornamento appropriata.



=== Aggiornare un nodo di gestione alla versione 12.5 o successiva dalla versione 12.3.x o successiva

È possibile eseguire un aggiornamento in-place del nodo di gestione dalla versione 12.3.x o successiva alla versione 12.5 o successiva senza dover eseguire il provisioning di una nuova macchina virtuale con nodo di gestione.


NOTE: Il nodo di gestione Element 12.5 o versione successiva è un aggiornamento opzionale. Non è richiesto per le implementazioni esistenti.

.Prima di iniziare
* La RAM della VM del nodo di gestione è di 24 GB.
* Il nodo di gestione che si intende aggiornare è la versione 12.0 e utilizza la rete IPv4. Il nodo di gestione versione 12.5 o successiva non supporta IPv6.
+

TIP: Per verificare la versione del nodo di gestione, accedere al nodo di gestione e visualizzare il numero di versione dell'elemento nel banner di accesso.

* Hai aggiornato il tuo bundle di servizi di gestione alla versione più recente utilizzando NetApp Hybrid Cloud Control. È possibile accedere a NetApp Hybrid Cloud Control dal seguente indirizzo IP: `\https://<ManagementNodeIP>`
* Se si sta aggiornando il nodo di gestione alla versione 12.5 o successiva, per procedere sono necessari i servizi di gestione 2.21.61 o successiva.
* È stato configurato un adattatore di rete aggiuntivo (se necessario) seguendo le istruzioni per link:task_mnode_install_add_storage_NIC.html["Configurazione di una scheda di rete storage aggiuntiva"].
+

NOTE: I volumi persistenti potrebbero richiedere un adattatore di rete aggiuntivo se eth0 non è in grado di essere instradato a SVIP. Configurare un nuovo adattatore di rete sulla rete di storage iSCSI per consentire la configurazione di volumi persistenti.

* I nodi di storage eseguono Element 12.3.x o versioni successive.


.Fasi
. Accedere alla macchina virtuale del nodo di gestione utilizzando l'accesso a SSH o alla console.
. Scaricare il https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["Nodo di gestione ISO"^] Per il software Element dal sito di supporto NetApp alla macchina virtuale del nodo di gestione.
+

NOTE: Il nome dell'ISO è simile a. `solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. Verificare l'integrità del download eseguendo md5sum sul file scaricato e confrontare l'output con quello disponibile sul NetApp Support Site per il software Element, come nell'esempio seguente:
+
`sudo md5sum -b <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. Montare l'immagine ISO del nodo di gestione e copiare il contenuto nel file system utilizzando i seguenti comandi:
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. Passare alla home directory e smontare il file ISO da `/mnt`:
+
[listing]
----
sudo umount /mnt
----
. Eliminare l'ISO per risparmiare spazio sul nodo di gestione:
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. Sul nodo di gestione che si sta aggiornando, eseguire il comando seguente per aggiornare la versione del sistema operativo del nodo di gestione. Lo script conserva tutti i file di configurazione necessari dopo l'aggiornamento, ad esempio le impostazioni di Active IQ Collector e proxy.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
Al termine del processo di aggiornamento, il nodo di gestione viene riavviato con un nuovo sistema operativo.

+

NOTE: Dopo aver eseguito il comando sudo descritto in questo passaggio, la sessione SSH viene terminata. L'accesso alla console è necessario per il monitoraggio continuo. Se non è disponibile alcun accesso alla console durante l'aggiornamento, riprovare a eseguire l'accesso SSH e verificare la connettività dopo 15 - 30 minuti. Una volta effettuato l'accesso, è possibile confermare la nuova versione del sistema operativo nel banner SSH che indica che l'aggiornamento è stato eseguito correttamente.

. Sul nodo di gestione, eseguire `redeploy-mnode` script per conservare le impostazioni di configurazione dei servizi di gestione precedenti:
+

NOTE: Lo script conserva la precedente configurazione dei servizi di gestione, inclusa la configurazione dal servizio di raccolta Active IQ, dai controller (vCenter) o dal proxy, a seconda delle impostazioni.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: Se in precedenza era stata disattivata la funzionalità SSH sul nodo di gestione, è necessario link:task_mnode_ssh_management.html["Disattivare nuovamente SSH"] sul nodo di gestione ripristinato. Funzionalità SSH che offre link:task_mnode_enable_remote_support_connections.html["Accesso alla sessione del NetApp Support Remote Support Tunnel (RST)"] è attivato sul nodo di gestione per impostazione predefinita.



=== Riconfigurare l'autenticazione utilizzando l'API REST del nodo di gestione

È possibile mantenere il nodo di gestione esistente se sono stati aggiornati in sequenza (1) servizi di gestione e (2) storage di elementi. Se si è seguito un ordine di aggiornamento diverso, consultare le procedure per gli aggiornamenti dei nodi di gestione in-place.

.Prima di iniziare
* I servizi di gestione sono stati aggiornati alla versione 2.20.69 o successiva.
* Il cluster di storage esegue Element 12.3 o versione successiva.
* I servizi di gestione sono stati aggiornati in sequenza, seguito dall'aggiornamento dello storage Element. Non è possibile riconfigurare l'autenticazione utilizzando questa procedura a meno che non siano stati completati gli aggiornamenti nella sequenza descritta.


.Fasi
. Aprire l'interfaccia utente REST API del nodo di gestione sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. Selezionare *autorizzare* e completare le seguenti operazioni:
+
.. Inserire il nome utente e la password del cluster.
.. Immettere l'ID client come `mnode-client` se il valore non è già compilato.
.. Selezionare *autorizzare* per avviare una sessione.


. Dall'interfaccia utente API REST, selezionare *POST /Services/reconfigure-auth*.
. Selezionare *Provalo*.
. Per il parametro *load_images*, selezionare `true`.
. Selezionare *Esegui*.
+
Il corpo della risposta indica che la riconfigurazione è stata eseguita correttamente.





== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Pagina delle risorse NetApp HCI"^]

