---
sidebar: sidebar 
permalink: docs/task_nde_supported_net_changes.html 
summary: 'Scopri le attività di post-implementazione da eseguire dopo l"implementazione di NetApp HCI.' 
keywords: netapp, hci, deployment, review, deploy 
---
= Modifiche di rete supportate
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver implementato NetApp HCI, è possibile apportare modifiche limitate alla configurazione di rete predefinita. Tuttavia, è necessario soddisfare alcuni requisiti per un funzionamento regolare e un corretto rilevamento della rete. Il mancato rispetto di questi requisiti causerà un comportamento imprevisto e potrebbe impedire l'espansione delle risorse di calcolo e storage.

Dopo aver implementato il sistema, è possibile apportare le seguenti modifiche alla configurazione di rete predefinita in VMware vSphere in base ai requisiti di rete:

* Modificare i nomi di vSwitch
* Modificare i nomi dei gruppi di porte
* Aggiungere e rimuovere gruppi di porte aggiuntivi
* Modificare l'ordine di failover dell'interfaccia vmnic per eventuali gruppi di porte aggiuntivi aggiunti


Quando si esegue la scalabilità di H300E, H500E, H700E, H410C, H610C, E i nodi di calcolo H615C, NetApp HCI prevede che il cluster di calcolo esistente sul nodo soddisfi i seguenti requisiti:

* Almeno quattro interfacce vmk
* Un'interfaccia vmk di gestione
* Un'interfaccia vmk vmotion
* Due vmk sulla stessa sottorete con associazioni iSCSI all'iniziatore iSCSI software


[NOTE]
====
A partire da NetApp HCI 1.10, quando si ridimensiona il cluster, NetApp HCI non prevede di soddisfare le configurazioni predefinite dei nodi.

Dopo aver modificato le impostazioni predefinite in VMware vSphere per uno o più nodi nel cluster di calcolo esistente, le impostazioni del nuovo nodo si allineeranno con quelle della maggior parte dei nodi nel cluster.

====


== Configurazioni predefinite del NetApp Deployment Engine

NetApp Deployment Engine imposta le configurazioni predefinite per gli host di calcolo in base alla configurazione del sistema e del cavo.



=== Nodi di calcolo H300E, H500E, H700E e H410C

Di seguito è riportata una configurazione a sei interfacce per i nodi H300E, H500E, H700E e H410C con VMware vSphere Distributed Switching (VDS). Questa configurazione è supportata solo se utilizzata con gli switch distribuiti VMware vSphere e richiede la licenza VMware vSphere Enterprise Plus.

|===
| Funzione di rete | vmkernel | vmnic (interfaccia fisica) 


| Gestione | vmk0 | Vmnic2 (porta A), vmnic3 (porta B) 


| ISCSI-A. | vmk1 | Vmnic5 (porta e) 


| ISCSI-B. | vmk2 | Vmnic1 (porta D) 


| VMotion | vmk3 | Vmnic4 (porta C), vmnic0 (porta F) 
|===
Di seguito è riportata una configurazione a sei interfacce con VMware vSphere Standard Switching (VSS). Questa configurazione utilizza VMware vSphere Standard Switch (VSS).

|===
| Funzione di rete | vmkernel | vmnic (interfaccia fisica) 


| Gestione | vmk0 | Vmnic2 (porta A), vmnic3 (porta B) 


| ISCSI-A. | vmk2 | Vmnic1 (porta e) 


| ISCSI-B. | vmk3 | Vmnic5 (porta D) 


| VMotion | vmk1 | Vmnic4 (porta C), vmnic0 (porta F) 
|===
Di seguito è riportata una configurazione a due interfacce. Questa configurazione è supportata solo se utilizzata con VMware vSphere Distributed Switch (VDS) e richiede la licenza VMware vSphere Enterprise Plus.

|===
| Funzione di rete | vmkernel | vmnic (interfaccia fisica) 


| Gestione | vmk0 | Vmnic1 (porta D), vmnic5 (porta e) 


| ISCSI-A. | vmk1 | Vmnic1 (porta e) 


| ISCSI-B. | vmk2 | Vmnic5 (porta D) 


| VMotion | vmk3 | Vmnic1 (porta C), vmnic5 (porta F) 
|===


=== Nodi di calcolo H610C

Questa configurazione per i nodi H610C è supportata solo se utilizzata con VMware vSphere Distributed Switch (VDS) e richiede la licenza VMware vSphere Enterprise Plus.


NOTE: Le porte A e B non sono utilizzate sul modello H610C.

|===
| Funzione di rete | vmkernel | vmnic (interfaccia fisica) 


| Gestione | vmk0 | Vmnic2 (porta C), vmnic3 (porta D) 


| ISCSI-A. | vmk1 | Vmnic3 (porta D) 


| ISCSI-B. | vmk2 | Vmnic2 (porta C) 


| VMotion | vmk3 | Vmnic2 (porta C), vmnic3 (porta D) 
|===


=== Nodi di calcolo H615C

Questa configurazione per i nodi H615C è supportata solo se utilizzata con VMware vSphere Distributed Switch (VDS) e richiede la licenza VMware vSphere Enterprise Plus.

|===
| Funzione di rete | vmkernel | vmnic (interfaccia fisica) 


| Gestione | vmk0 | Vmnic0 (porta A), vmnic1 (porta B) 


| ISCSI-A. | vmk1 | Vmnic0 (porta B) 


| ISCSI-B. | vmk2 | Vmnic1 (porta A) 


| VMotion | vmk3 | Vmnic0 (porta A), vmnic1 (porta B) 
|===


== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://www.netapp.com/us/documentation/hci.aspx["Pagina delle risorse NetApp HCI"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"^]

